project_name: hacompanion
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.Version={{.Version}}
    goos:
      - linux
#      - windows
#      - darwin
nfpms:
  - package_name: hacompanion
    maintainer: Tobias Kuendig <tobias@offline.ch>
    description: Desktop Companion for Home Assistant.
    formats:
      - deb
      - rpm
    license: MIT
    dependencies:
      - lm-sensors
      - iputils-ping
      - libnotify-bin
archives:
  - format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
