[homeassistant]
device_name = "Dell Desktop"
token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiIzZGQyNGFhMWZiOWY0NjhjYWU2YjBmMDYwMGVkOGU1ZiIsImlhdCI6MTYyMDIzODA3MSwiZXhwIjoxOTM1NTk4MDcxfQ.acv3qSoz9IdLVN6oJofTafMPovqGri-L1Efrk3Q255w"
host = "http://192.168.1.77:8123"

[companion]
update_interval = "15s"
notification_server = "http://192.168.1.2:8080/notifications"
registration_file = "~/.config/ha-registration.json"

[sensor.webcam]
enabled = true
name = "Webcam Process Count"

# Requires lm-sensors package to be installed
[sensor.cpu_temp]
enabled = true
name = "CPU Temperature"
meta = { celsius = true }

[sensor.cpu_usage]
enabled = true
name = "CPU Usage"

[sensor.uptime]
enabled = true
name = "Last Boot"

[sensor.memory]
enabled = true
name = "Memory"

[sensor.power]
enabled = true
name = "Power"
meta = { battery = "BAT0" }

[sensor.companion_running]
enabled = true
name = "Companion Is Running"

[sensor.online_check]
enabled = true
name = "Is Online"
# mode is http or ping
meta = { target = "https://google.com", mode = "http" }

[sensor.load_avg]
enabled = true
name = "Load Avg"

[sensor.audio_volume]
enabled = true
name = "Audio Volume"

[sensor.script]
enabled = false

[sensor.script.meta]
scripts = [
    "abc",
    "def",
]


