device_name = "Dell Laptop"
token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiIzZGQyNGFhMWZiOWY0NjhjYWU2YjBmMDYwMGVkOGU1ZiIsImlhdCI6MTYyMDIzODA3MSwiZXhwIjoxOTM1NTk4MDcxfQ.acv3qSoz9IdLVN6oJofTafMPovqGri-L1Efrk3Q255w"
host = "http://192.168.1.77:8123"

[sensor.webcam]
enabled = true
name = "Webcam Process Count"

# Requires lm-sensors package to be installed
[sensor.cpu_temp]
enabled = true
name = "CPU Temperature"
meta = { celcius = true }

[sensor.memory]
enabled = true
name = "Memory"

[sensor.power]
enabled = true
name = "Power"
meta = { battery = "BAT0" }

#[sensor.powered_on]
#enabled = true
#name = "Powered On"

#[sensor.online]
#enabled = true
#name = "Is Online"
#meta = { host = "google.com" }

[sensor.load_avg]
enabled = true
name = "Load Avg"

[sensor.audio_volume]
enabled = true
name = "Audio Volume"

[sensor.script]
enabled = false

[sensor.script.meta]
scripts = [
    "abc",
    "def",
]


